export const GET_ROUTES_REQUESTED = 'GET_ROUTES_REQUESTED'
export const GET_ROUTES = 'GET_ROUTES'
export const SET_ROUTE_ID = 'SET_ROUTE_ID'
export const SHOW_DIRECTION_DROP_DOWN = 'SHOW_DIRECTION_DROP_DOWN'

export const GET_DIRECTIONS_REQUESTED = 'GET_DIRECTIONS_REQUESTED'
export const GET_DIRECTIONS = 'GET_DIRECTIONS'
export const SET_DIRECTION_ID = 'SET_DIRECTION_ID'
export const SHOW_STOPS_DROPDOWN = 'SHOW_STOPS_DROPDOWN'

export const GET_STOPS_REQUESTED = 'GET_STOPS_REQUESTED'
export const GET_STOPS = 'GET_STOPS'
export const SET_STOP_ID = 'SET_STOP_ID'
export const SHOW_DEPARTURES_TABLE = 'SHOW_DEPARTURES_TABLE'

export const GET_DEPARTURES_REQUESTED = 'GET_DEPARTURES_REQUESTED'
export const GET_DEPARTURES = 'GET_DEPARTURES'

export const RESET_ROUTE_DATA = 'RESET_ROUTE_DATA'
export const RESET_DIRECTION_DATA = 'RESET_DIRECTION_DATA'
export const RESET_STOP_DATA = 'RESET_STOP_DATA'
