export const types = {
  GET_ROUTES_REQUESTED: 'GET_ROUTES_REQUESTED',
  GET_ROUTES: 'GET_ROUTES',
  GET_DIRECTIONS_REQUESTED: 'GET_DIRECTIONS_REQUESTED',
  GET_DIRECTIONS: 'GET_DIRECTIONS',
  GET_STOPS_REQUESTED: 'GET_STOPS_REQUESTED',
  GET_STOPS: 'GET_STOPS',
  GET_DEPARTURES_REQUESTED: 'GET_DEPARTURES_REQUESTED',
  GET_DEPARTURES: 'GET_DEPARTURES',
  SET_LOADING: 'SET_LOADING'
}
